name: Automated Release
on:
  push:
    branches:
      - "main"
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.0.5 [CE|EE|ECE 2.4.0-2.4.7] 12 Jun 2024
          tag_name: 1.0.5
          body: |-
            - **Compatibility**: Add dependency for `SoftCommerce_SeoSuite`;
            - **Fix**: Fix dependency module sequence component name declaration for `Magento_PageBuilder` in module.xml [#7]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
