name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.2.11 [CE|EE|ECE 2.4.0-2.4.7] 21 Mar 2024
          tag_name: 1.2.11
          body: |-
            ### softcommerce/module-graphcommerce-cms [1.0.0]
            - **Compatibility**: Introduced support for PHP 8.3 [#2]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
