name: Automated Release
on:
  push:
    branches:
      - "main"
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.0.3 [CE|EE|ECE 2.4.0-2.4.7] 28 May 2024
          tag_name: 1.0.3
          body: |-
            ### softcommerce/module-graphcommerce-cms [1.0.3]
            - **Feature**: Add support of custom pagebuilder elements for categories [#4]
            - **Feature**: Add `CmsRowServiceLinks` element to pagebuilder to enable creation of service links [#3]
            - **Feature**: Add `CmsRowText` component to pagebuilder to enable creation of rich text AST elements [#2]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
