name: Automated Release
on:
  push:
    branches:
      - "main"
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.0.4 [CE|EE|ECE 2.4.0-2.4.7] 29 May 2024
          tag_name: 1.0.4
          body: |-
            - **Enhancement**: Add version requirements for `softcommerce/module-core` module [#5]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
