name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.0.1 [CE|EE|ECE 2.4.0-2.4.7] 13 May 2024
          tag_name: 1.0.1
          body: |-
            - **Enhancement**: Introduced support of custom scalar types for GraphQL schema [#1]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
