name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.0.2 [CE|EE|ECE 2.4.0-2.4.7] 18 May 2024
          tag_name: 1.0.2
          body: |-
            ### softcommerce/module-graphcommerce-cms [1.0.2]
            - **Enhancement**: Remove dependency for `softcommerce/module-profile` in favour of `softcommerce/module-core`.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
